version: "3.6"

services:
  nginx_ssl:
    container_name: nginx_ssl
    image: nginx:latest
    network_mode: host
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/ssl
  hello:
    image: hashicorp/http-echo
    network_mode: host
    command: ["-listen=:8000", "-text=merhabayalandunya"]