version: "3.6"

services:
  # single proxy, single config for all apps
  nginx_proxy:
    container_name: nginx_proxy
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
  app:
    container_name: app
    build: .
    command: ["node", "app.js"]
    